name: "Publish docker image"
description: "Pushes built artifacts to DockerHub"
inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "DOCKERHUB_IMAGE_NAME=${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - shell: bash
      run: docker build -t "${DOCKERHUB_IMAGE_NAME}:latest" -t "${DOCKERHUB_IMAGE_NAME}:${GITHUB_SHA::8}" ./target

    - shell: bash
      run: docker login -u ${{inputs.registry_username}} -p ${{inputs.registry_password}}

    - shell: bash
      run: docker push --all-tags "${GITHUB_REPOSITORY_OWNER,,}/${REPOSITORY_NAME}"
